# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  isMainBranch: eq(variables['Build.SourceBranch'], 'refs/heads/main')

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: Pipeline
        steps:
        - task: SonarCloudPrepare@4
          condition: variables['isMainBranch']
          displayName: 'Prepare SonarQube Analysis'
          inputs:
            SonarCloud: 'SonarQubeConnection'
            organization: 'benlinfinity'
            scannerMode: 'dotnet'
            projectKey: 'BenLinfinity_AzureDevOps'
            projectName: 'AzureDevOps'

        - task: UseDotNet@2
          displayName: 'Install .NET Core SDK'
          inputs:
            packageType: 'sdk'
            version: '10.x'

        - script: |
            npx semantic-release
          env:
            GH_TOKEN: $(GITHUB_TOKEN_SECRET)
            displayName: 'Run Semantic Release'

        - script: |
            git fetch --tags
            LATEST_TAG=$(git describe --tags --abbrev=0)
            echo "The newly released version is: $LATEST_TAG"
            
            CLEAN_VERSION=$(echo "$LATEST_TAG" | sed 's/^v//')
            echo "Clean SemVer for Azure Artifacts: $CLEAN_VERSION"

            # Optional: Expose it as an Azure DevOps variable for subsequent tasks
            echo "##vso[task.setvariable variable=NewVersion]$CLEAN_VERSION"
          displayName: 'Print and Capture Version'

        - task: DotNetCoreCLI@2
          inputs:
            command: 'build'
            arguments: > 
              --configuration $(buildConfiguration)
              -p:Version=$(NewVersion) -p:AssemblyVersion=$(NewVersion)
              -p:PackageId=$(Build.SourceBranchName)_$(NewVersion)
          displayName: 'dotnet build $(buildConfiguration)'

        - task: UniversalPackages@0
          displayName: 'Publish to Azure Artifacts Feed'
          inputs:
            command: 'publish'
            publishDirectory: '$(Build.ArtifactStagingDirectory)'
            feedsToUsePublish: 'internal'
            vstsFeedPublish: 'Azure-Pipeline/HelloApp'
            vstsFeedPackagePublish: 'hello-app-zip'
            versionOption: 'custom'
            versionPublish: '$(NewVersion)'

        - task: SonarCloudAnalyze@4
          condition: variables['isMainBranch']
          displayName: 'Run SonarQube Code Analysis'

        - task: SonarCloudPublish@4
          condition: variables['isMainBranch']
          displayName: 'Publish Quality Gate Result'
          inputs:
            pollingTimeoutSec: '300'

        - task: DotNetCoreCLI@2
          condition: variables['isMainBranch']
          displayName: 'Pack NuGet Package'
          inputs:
            command: 'pack'
            packagesToPack: '**/*.csproj'
            configuration: '$(buildConfiguration)'
            packDirectory: '$(Build.ArtifactStagingDirectory)'
            outputDir: '$(Build.ArtifactStagingDirectory)'
            buildProperties: 'Version=$(NewVersion);PackageVersion=$(NewVersion);PackageId=$(Build.SourceBranchName)_$(NewVersion)'
        - script: |
            echo "Package: $(Build.SourceBranchName)_$(NewVersion)"
          displayName: "Print Package Name"
        - task: DotNetCoreCLI@2
          displayName: 'Push to Azure Artifacts'
          inputs:
            command: 'push'
            searchPatternPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
            feedPublish: 'hello-app-nuget'


          



